### ISSUE TITLE
shouldEndSession is broken

### ISSUE THREAD

**Issue by n0dyjeff** [erik/alexandra#5]
shouldEndSession is always seen by Alexa as True. The json response body has "shouldEndSession" incorrectly at the first level, but it should be an element of the "response" element, and at the same level as "output speech" and "reprompt".  See https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/alexa-skills-kit-interface-reference.

**Comment by erik** [comment]
Thanks again for reporting! Fixed by your PR, #6
