### ISSUE TITLE
pyOpenSSL version >= 16.1.0 required

### ISSUE THREAD

**Issue by n0dyjeff** [erik/alexandra#7]
Live requests from Alexa fail to validate the cryptographic request signature with the specified version of the pyOpenSSL library (0.15.1). The same is true for 16.0.0. **It appears that pyOpenSSL>=16.1.0 is required**, although I haven't taken the time to find out why exactly. I've confirmed correct operation with both 16.1.0 and 16.2.0

Following is log output of the :bomb: error (same for either 0.15.1 or 16.0.0):
`12/26/2016 11:15:34 PM alexandra.util ERROR    invalid request signature`
`12/26/2016 11:15:34 PM alexandra.wsgi ERROR    failed to validate request`
`12/26/2016 11:15:34 PM alexandra.wsgi ERROR    Failed to handle request`
`Traceback (most recent call last):`
 ` File "/home/jeff/.virtualenvs/yams/lib/python3.5/site-packages/alexandra/wsgi.py", line 66, in wsgi_app
    abort(403)`
`  File "/home/jeff/.virtualenvs/yams/lib/python3.5/site-packages/werkzeug/exceptions.py", line 646, in __call__
    raise self.mapping[code](*args, **kwargs)`
`werkzeug.exceptions.Forbidden: 403: Forbidden`
``

**Comment by erik** [comment]
Thanks again for reporting the issue. Sorry about these low hanging fruit sort of issues, it's been a while now since I've used an echo device so seems like things have changed.

I'll try to do some more extensive testing this week to shake out some more issues, but please continue reporting whatever you find

**Comment by n0dyjeff** [comment]
Thanks for the lightning fast response. I'll definitely let you know if I see anything else, but this is it so far.  Thanks again for sharing.
